name: pkgdown public ghpages

on:
  workflow_call:
    inputs:
      folder:
        type: string
        description: 'where your pkgdown site is stored'
        required: false
        default: 'docs'
      extra_pkgs:
        type: string
        description: |
          extra packages to install, separated by commas. One may use `any::` prefix to
          inadicate any source is okay. Read https://github.com/r-lib/actions/tree/v2/setup-r-dependencies
        required: false
        default: ''

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: parse extra packages string
        shell: bash
        run: |
        
          if [[ "${{ inputs.extra_pkgs }}" == "" ]]; then
            pkgs="any::pkgdown, local::."
          else
            pkgs="any::pkgdown, local::., ${{ inputs.extra_pkgs }}"
          fi
          echo "EXTRA_PKGS=$pkgs" >> "$GIT_ENV"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: ${{ env.EXTRA_PKGS }}
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: ${{ inputs.folder }}

        
